/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hotdog;

public class pydiff {

    public static void main(String[] args) {
        new pydiff().run();
    }

    public void run() {
        /*
        cli.parse option
        GitInformation . get Changed File list according to the commit
        File.parse
        diff (AST1, AST2)
        analyze. changeAnalyze()
         */
    }
}
