/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hotdog;

import hotdog.git.GitInformation;
import hotdog.io.CLI;
import hotdog.io.CSV;

import java.util.ArrayList;

public class pydiff {
    private String workPath;

    public static void main(String[] args) {
        new pydiff().run(args);
    }

    public void run(String[] args) {
        CLI cli = new CLI(args);
        workPath = cli.getWorkPath();

//        if (cli.multiplePairs) {
//            runMulitplePairs(cli.getCsvPath());
//        }
//        else if (cli.singlePair) {
//            runSinglePair(cli.getSinglePairInfo());
//        }
        /*
        cli.parse option
        GitInformation . get Changed File list according to the commit
        File.parse
        diff (AST1, AST2)
        String editscript = analyze. changeAnalyze()
        String diff = diff().toString()
         */
    }

    private void runMulitplePairs(String csvPath) {
        // csv read
        ArrayList<String[]> csvContents = new CSV().readContents(csvPath);
    }

    private void runSinglePair(String[] singlePairInfo) {
        new GitInformation().collect(workPath, singlePairInfo);
    }
}
