/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hotdog;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        pydiff classUnderTest = new pydiff();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
